### ISSUE TITLE
can't open psxprev Exception non gérée : System.AccessViolationException: Tentative de lecture ou d'écriture de mémoire protégée. 

### ISSUE THREAD

**Issue by Endymi0n74** [rickomax/psxprev#170]
Exception non gérée : System.AccessViolationException: Tentative de lecture ou d'écriture de mémoire protégée. Cela indique souvent qu'une autre mémoire est endommagée.
   à OpenTK.Graphics.OpenGL.GL.CreateProgram()
   à PSXPrev.Common.Renderer.Scene.SetupShaders()
   à PSXPrev.Common.Renderer.Scene.Initialize(Single width, Single height)
   à PSXPrev.Forms.PreviewForm.openTKControl_Load(Object sender, EventArgs e)
   à System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   à System.Windows.Forms.UserControl.OnCreateControl()
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl()
   à System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   à System.Windows.Forms.TabPage.set_Visible(Boolean value)
   à System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   à System.Windows.Forms.TabControl.OnHandleCreated(EventArgs e)
   à System.Windows.Forms.Control.WmCreate(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.TabControl.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Endymi0n74** [comment]
nvm rebooted pc and worked

**Comment by trigger-segfault** [comment]
Thanks for letting us know that that solved the issue. That's good to know for any other similar issues that pop up. :)
