### ISSUE TITLE
Crash after scan end

### ISSUE THREAD

**Issue by joelgomes1994** [rickomax/psxprev#18]
(Desculpa se eu estiver floodando seus issues, tô tentando ajudar reportando problemas... :sweat_smile: )

Isso acontece sempre após um scan terminado.

![image](https://user-images.githubusercontent.com/19820741/36398313-36fbe5fc-15a5-11e8-9f8b-280e0fbe06c7.png)

Texto de exceção:

OpenTK.Graphics.GraphicsContextException: Invalid window
   em OpenTK.Platform.SDL2.Sdl2GraphicsContext..ctor(GraphicsMode mode, IWindowInfo win, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   em OpenTK.Platform.SDL2.Sdl2Factory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   em OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   em OpenTK.Sdl2GLControl.CreateContext(Int32 major, Int32 minor, GraphicsContextFlags flags)
   em OpenTK.GLControl.OnHandleCreated(EventArgs e)
   em System.Windows.Forms.Control.WmCreate(Message& m)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   em System.Windows.Forms.ContainerControl.WndProc(Message& m)
   em System.Windows.Forms.UserControl.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rickomax** [comment]
Me passa qual seu sistema operacional, e também o modelo da sua placa de vídeo.

**Comment by joelgomes1994** [comment]
Xi, modelo de placa de vídeo não sei dizer, mas sistema, memória e processador são os seguintes:
![image](https://user-images.githubusercontent.com/19820741/36402506-d0181702-15bd-11e8-9b87-3a04d81d784c.png)

**Comment by rickomax** [comment]
Pode ser que sua placa de vídeo não suporte o OpenGL 3.0
No caso, você teria que baixar um pacote do Mesa Drivers e instalar/extrair na pasta do executável do PSXPREV.
Eu até ajudaria nisso, mas to meio apertado aqui.

**Comment by rickomax** [comment]
Esse instalador parece ser para o Windows:
https://github.com/pal1000/mesa-dist-win/releases/download/17.3.5.501-1/mesa-17.3.5.501-1-sfx.exe

**Comment by joelgomes1994** [comment]
Testei como instruído: extraí e colei os drivers na pasta do PSXPREV (primeiro os x64, depois os x86) e rodei  o scan. Em ambos os casos (drivers x64 e x86) deu o mesmo resultado. O estranho é que meu laptop suporta até o OpenGL 3.1.

![image](https://user-images.githubusercontent.com/19820741/36512405-07b8ec4a-1749-11e8-93fb-6e14bd472751.png)

Na sua postagem [no seguinte fórum](https://www.vg-resource.com/thread-29559.html) você diz que precisa de uma versão de OpenGL 2.0. Você ainda tem essa versão mais antiga para eu testar?

**Comment by rickomax** [comment]
Não sei ao certo o que acontece no seu caso, o aplicativo está configurado para utilizar o OpenGL 3.0.

**Comment by rickomax** [comment]
Uma nova versão está disponível em releases. Aconselho baixar e refazer os testes.
