### ISSUE TITLE
Does not scan

### ISSUE THREAD

**Issue by lemurboy12** [rickomax/psxprev#19]
![image](https://user-images.githubusercontent.com/12989755/38256821-018e6e54-3714-11e8-94c6-084804c67203.png)

When I scan, it immediately gives up and doesn't scan anything. What should I do?

**Comment by rickomax** [comment]
The console output means there are no models/textures and animations found. The application will close on these cases.

**Comment by krendil** [comment]
You haven't specified the `filter` argument.  Or rather, you have, but the filter you've given is `[-tmd]`.  Unless you have a file called `[-tmd]`, no files will be scanned.  Instead, try the following command:
```
PSXPrev arthur *.* -tmd -pmd -tim -retim -tod -hmdmodels -log
```

_I realise OP has probably moved on, but I'll leave this comment for posterity, as I experienced the same issue._

**Comment by rickomax** [comment]
Ty @krendil. I'll mark as resolved.
