### ISSUE TITLE
Can't get Rascal (PS1) model

### ISSUE THREAD

**Issue by SuperWiiBros08** [rickomax/psxprev#23]
I wanna get the player model of the game Rascal, I extracted the files of the .bin image with jPSXdec and scanned them all on a folder with PSXPrev, but it doesn't give any models and all the textures appear corrupted
![1](https://user-images.githubusercontent.com/52180523/71197947-06edb500-2293-11ea-865a-82e79f3fb83f.PNG)
![2](https://user-images.githubusercontent.com/52180523/71197953-08b77880-2293-11ea-96f0-df8833ac7b31.PNG)
![3](https://user-images.githubusercontent.com/52180523/71197959-0b19d280-2293-11ea-9f87-b78b12d112d2.PNG)

**Comment by rickomax** [comment]
Hi!

PSXPrev won't work with every single game, the models/textures/animation you got are probably false positives, as it uses a approximation approach to scan the files.

**Comment by SuperWiiBros08** [comment]
Gotcha, thanks for the reply!
