### ISSUE TITLE
What is the best method of contact?

### ISSUE THREAD

**Issue by Squall789** [rickomax/psxprev#24]
Sorry to bother you, I have some files from Breath of Fire IV.
I've been successfully able to extract them from the BMI files without issue, but it looks like the files inside are an unknown format to me.

I was wondering if there might be a way to upload a few for you to look into, if its not too much trouble.

I was wondering what the best way to do that might be.

**Comment by rickomax** [comment]
PSXPREV is meant to deal with default PSX SDK file formats only; I'm not used to 3D file formats studying.
