### ISSUE TITLE
Texture Issues

### ISSUE THREAD

**Issue by Aevum11** [rickomax/psxprev#25]
In some images, there is a bar going through it that ruins the image and they almost seem like scanlines. It completely ruins some texture. I can upload a picture if needed. The game was Legend of Dragoon. I used the most recent version of this program. Is there a way to fix this or is it a bug? I really need the textures and your tool is the greatest I've found and I thank you for making it.

**Comment by rickomax** [comment]
Hi!
It's probably finding data that ressembles TIM textures, but aren't TIM textures at all.
