### ISSUE TITLE
Export all detected models/textures/etc

### ISSUE THREAD

**Issue by IvanDSM** [rickomax/psxprev#26]
It would be nice to have an option to export all detected models instead of just selected ones, especially when dealing with files with a large amount of models.

I'd try to implement this myself but I'm unable to compile the program under Linux :/

**Comment by rickomax** [comment]
I will check it out soon.

**Comment by trigger-segfault** [comment]
This was implemented in PR #137. (Although animations are still on a per-selection basis)
