### ISSUE TITLE
Feature request: Support for Namco's file formats (used in Tekken 1/2/3 and Soul Edge)

### ISSUE THREAD

**Issue by spaztron64** [rickomax/psxprev#28]
Nothing online seems to be able to convert these models into usable formats, or even be able to extract them from the BNS archive files they're in (apart from that Tekken 2 BNS extractor tool that unfortunately only supports that game).

**Comment by rickomax** [comment]
Hi!
PSXPREV goal is to work with well-known PSX file formats only, I'm not used to 3D file formats studying.
