### ISSUE TITLE
Legend Of Legaia Preview Models not working

### ISSUE THREAD

**Issue by wolinger** [rickomax/psxprev#32]
Hi @rickomax im trying to use your software to read and extract some models and animations from Legend Of Legaia but when i scan in console say "found at offset", i can see the list but when i click to preview, model its not generated, can you try implement this? Thanks.

**Comment by rickomax** [comment]
Hi!
PSXPREV only works with PSX SDK default file formats, any game which doesn't use them is not supported.
I'm sorry, I don't have much time lately to adapt more file formats.
