### ISSUE TITLE
Exported OBJ models are always merged

### ISSUE THREAD

**Issue by Jaffacakelover** [rickomax/psxprev#38]
My example is Chris Redfield's character model from Resident Evil 1. It consists of 1 EMD model and 19 Sub-Models.
*Ignoring that all Sub-Models are centered for now - assuming their positioning can be fixed using animations somehow.*

![2021-10-14 21_59_03-PSXPrev Alpha 0 9 8 2](https://user-images.githubusercontent.com/3490850/137395944-2c48fe1f-a641-49c9-843f-8edca6860791.png)

I tick the checkbox for this model and use `Models > Export Selected > Wavefront.OBJ`. The existence of the `Wavefront.OBJ - Merged` options suggests that the option I picked will produce "un-merged". However, when I import the resulting OBJ file into Blender, all of the Sub-Models have been merged into 1 mesh.

![2021-10-14 22_00_33-Blender](https://user-images.githubusercontent.com/3490850/137395984-ba284047-4651-4f60-9e27-c462b7e27269.png)

This limitation looks to be due to the contents of the exported OBJ file, rather than Blender's import function.

The program will not let me export Sub-Models individually, only Models.

Is it possible for the export to create the Sub-Models as seperate objects within an OBJ file, or even as 1 OBJ file per Sub-Model?

**Comment by trigger-segfault** [comment]
This feature has been added in the latest public release: https://github.com/rickomax/psxprev/releases/tag/0.9.9.2

You can change this by selecting the clicking the **Group by Model** dropdown and selecting **Split by TMD ID**.
