### ISSUE TITLE
Croc model files not extracting

### ISSUE THREAD

**Issue by orange451** [rickomax/psxprev#41]
I am trying to extract resources from the game Army Men 3D. I see .TOM texture, .TIM images, and .VDF animations
However, if I leave .Croc checked, the extractor gets stuck for hours on them. They never successfully process.

**Comment by orange451** [comment]
@rickomax did you die?

**Comment by rickomax** [comment]
I'm alive..haha

Unfortunately, I can't give support to PSXPrev, so I'm hoping the community helps me out fixing these issues.
