### ISSUE TITLE
Gizmo translation does not follow axis for hierarchical models

### ISSUE THREAD

**Issue by trigger-segfault** [rickomax/psxprev#50]
**Describe the issue:**
When using the translate gizmo on a model entity that uses a non-identity/translation-only matrix transform, the model entity will spaz out (sometimes clamping to random positions instead of moving along the selected axis.

**Solution:**
The issue is the order of the matrix multiplication during `Entitybase.ApplyTranslation`. Although examples will say to multiply `translation * rotation * scale`, the opposite is true for PSXPrev, probably because of the column vs. row usage for matrices.

```cs
// Original
//LocalMatrix = translation * rotation * scale;
// New
LocalMatrix = scale * rotation * translation;
```

**Video example:**
*Translating a part that doesn't follow the selected axis*

https://github.com/rickomax/psxprev/assets/9752430/609f8e73-61e1-45f3-9e5d-38a7634c3d5d

**Comment by rickomax** [comment]
Have you added that to your latest pull-requests?
I wasn't used to matrices when I've written PSXPrev code, but I'm aware the matrix multiplication order is wrong, and I guess I did it like that back in the day because I didn't know about homogeneous coodinates, etc.

**Comment by trigger-segfault** [comment]
I haven't added it. I was planning to make a separate PR for it (or let it get fixed by someone else) since it was a more general issue that could affect non-HMD models.  And that PR was dedicated to HMD.

And yeah, matrices are hard.

I should have added that there's a more general issue that appears after correcting this, that causes transforms with rotation/scaling to slightly rotate little by little as you translate the model over an axis. The best way to fix that would probably be to store the actual rotation, translation, and scaling when LocalMatrix is first-assigned, and then use that for when changing the transform.

**Comment by trigger-segfault** [comment]
Anyway, I don't mind getting assigned to this, since I've already messed with it for a bit.

**Comment by rickomax** [comment]
Thanks for your contribution!
